In [39]:
# basic libraries
import pandas as pd
import numpy as np

# visualization
import matplotlib.pyplot as plt
import seaborn as sns

# preprocessing
from sklearn.preprocessing import StandardScaler

# dbscan model
from sklearn.cluster import DBSCAN

# evaluation
from sklearn.metrics import silhouette_score

# optional: PCA for 2D visualization
from sklearn.decomposition import PCA

In [40]:
df = pd.read_csv("F:\\01. The Data Psychology\\4. New_Machine_Learning\\11. Clustering\\amazon_clustering.xls")

In [41]:
df.head()

,Unnamed: 0,product_id,product_name,category,price,discount_pct,final_price,rating,num_reviews,delivery_days,is_prime,was_returned,wishlist_count,cart_add_count
0,0,AMZN0001,T-Shirt,Clothing,2060.34,20,1648.27,4.9,2201,2,0,0,377,419
1,1,AMZN0002,Kurta,Clothing,3113.69,30,2179.58,3.3,484,1,0,0,111,119
2,2,AMZN0003,Smartwatch,Electronics,9356.27,15,7952.83,4.8,3025,7,1,0,229,2413
3,3,AMZN0004,Cricket Bat,Sports,14278.22,10,12850.40,3.5,970,7,1,1,142,159
4,4,AMZN0005,Comics,Books,682.71,5,648.57,4.1,280,1,1,0,183,176

In [42]:
df = df.drop(['Unnamed: 0','product_id'], axis= 1)

In [43]:
df.head()

,product_name,category,price,discount_pct,final_price,rating,num_reviews,delivery_days,is_prime,was_returned,wishlist_count,cart_add_count
0,T-Shirt,Clothing,2060.34,20,1648.27,4.9,2201,2,0,0,377,419
1,Kurta,Clothing,3113.69,30,2179.58,3.3,484,1,0,0,111,119
2,Smartwatch,Electronics,9356.27,15,7952.83,4.8,3025,7,1,0,229,2413
3,Cricket Bat,Sports,14278.22,10,12850.40,3.5,970,7,1,1,142,159
4,Comics,Books,682.71,5,648.57,4.1,280,1,1,0,183,176

In [44]:
df.tail()

,product_name,category,price,discount_pct,final_price,rating,num_reviews,delivery_days,is_prime,was_returned,wishlist_count,cart_add_count
1995,Comics,Books,109.81,40,65.89,4.5,1399,3,1,1,357,398
1996,Bedsheet,Home & Kitchen,10156.23,15,8632.80,4.7,56,7,0,0,250,36
1997,Action Figure,Toys,2801.67,25,2101.25,4.0,1257,5,0,1,384,303
1998,Shampoo,Beauty,355.81,50,177.91,4.4,2025,4,1,1,34,920
1999,Dal,Grocery,776.89,20,621.51,4.2,1280,7,0,1,434,120

In [45]:
df.dtypes

product_name          str
category              str
price             float64
discount_pct        int64
final_price       float64
rating            float64
num_reviews         int64
delivery_days       int64
is_prime            int64
was_returned        int64
wishlist_count      int64
cart_add_count      int64
dtype: object

In [46]:
X = df.select_dtypes(include='number')

In [47]:
X.head()

,price,discount_pct,final_price,rating,num_reviews,delivery_days,is_prime,was_returned,wishlist_count,cart_add_count
0,2060.34,20,1648.27,4.9,2201,2,0,0,377,419
1,3113.69,30,2179.58,3.3,484,1,0,0,111,119
2,9356.27,15,7952.83,4.8,3025,7,1,0,229,2413
3,14278.22,10,12850.40,3.5,970,7,1,1,142,159
4,682.71,5,648.57,4.1,280,1,1,0,183,176

In [48]:
scl = StandardScaler()

In [49]:
x_scl = scl.fit_transform(X)

In [50]:
x_scl

array([[-0.42123724, -0.09897113, -0.40971566, ..., -1.02840321,
         0.92379287, -0.4152971 ],
       [-0.35010284,  0.54684377, -0.36506978, ..., -1.02840321,
        -0.91941353, -0.69388443],
       [ 0.0714685 , -0.42187859,  0.12005532, ..., -1.02840321,
        -0.10175054,  1.43638003],
       ...,
       [-0.37117405,  0.22393632, -0.37165184, ...,  0.97238125,
         0.9722983 , -0.52301753],
       [-0.53634686,  1.83847358, -0.53326973, ...,  0.97238125,
        -1.45297327,  0.04994374],
       [-0.50791066, -0.09897113, -0.49599411, ...,  0.97238125,
         1.31876567, -0.69295581]], shape=(2000, 10))

In [17]:
DB = DBSCAN()

In [18]:
DB.fit(x_scl)

DBSCAN()

In [19]:
DB.labels_

array([-1, -1, -1, ..., -1, -1, -1], shape=(2000,))

In [51]:
# basic dbscan model
dbscan = DBSCAN(eps=1.2, min_samples=5)

# fit and predict clusters
clusters = dbscan.fit_predict(x_scl)

# cluster labels
print(clusters[:20])

[ 0  0 -1  1  2  3 11  1  3  0  2 -1  2  1  0  1 -1 -1  0 -1]

In [52]:
# add cluster labels to original data
df["cluster"] = clusters

In [53]:
df.head(10)

,product_name,category,price,discount_pct,final_price,rating,num_reviews,delivery_days,is_prime,was_returned,wishlist_count,cart_add_count,cluster
0,T-Shirt,Clothing,2060.34,20,1648.27,4.9,2201,2,0,0,377,419,0
1,Kurta,Clothing,3113.69,30,2179.58,3.3,484,1,0,0,111,119,0
2,Smartwatch,Electronics,9356.27,15,7952.83,4.8,3025,7,1,0,229,2413,-1
3,Cricket Bat,Sports,14278.22,10,12850.40,3.5,970,7,1,1,142,159,1
4,Comics,Books,682.71,5,648.57,4.1,280,1,1,0,183,176,2
5,Cricket Bat,Sports,3994.73,40,2396.84,4.0,531,5,0,1,40,300,3
6,Sunscreen,Beauty,1381.04,15,1173.88,3.6,2457,7,0,0,338,933,11
7,Cricket Bat,Sports,3134.08,15,2663.97,3.9,375,1,1,1,232,325,1
8,Face Cream,Beauty,1449.80,25,1087.35,4.6,818,3,0,1,359,699,3
9,Kurta,Clothing,2716.90,10,2445.21,4.2,158,5,0,0,236,97,0

In [54]:
# cluster count
print(df["cluster"].value_counts())

cluster
-1     734
 1     338
 3     308
 0     303
 2     281
 7       6
 10      5
 8       5
 4       5
 9       5
 6       4
 11      3
 5       3
Name: count, dtype: int64

In [55]:
# number of clusters (excluding noise)
n_clusters = len(set(clusters)) - (1 if -1 in clusters else 0)

# number of noise points
n_noise = list(clusters).count(-1)

print("Number of clusters:", n_clusters)
print("Number of noise points:", n_noise)

Number of clusters: 12
Number of noise points: 734

In [56]:
df.columns

Index(['product_name', 'category', 'price', 'discount_pct', 'final_price',
       'rating', 'num_reviews', 'delivery_days', 'is_prime', 'was_returned',
       'wishlist_count', 'cart_add_count', 'cluster'],
      dtype='str')

In [57]:
features = ['price', 'discount_pct', 'final_price',
       'rating', 'num_reviews', 'delivery_days', 'is_prime', 'was_returned',
       'wishlist_count', 'cart_add_count']

In [58]:
features

['price',
 'discount_pct',
 'final_price',
 'rating',
 'num_reviews',
 'delivery_days',
 'is_prime',
 'was_returned',
 'wishlist_count',
 'cart_add_count']

In [60]:
# cluster-wise average values
cluster_summary = df.groupby("cluster")[features].mean()

print(cluster_summary)

                price  discount_pct   final_price    rating  num_reviews  \
cluster
-1       15587.885463     22.513624  12222.098583  4.135014  2917.678474
 0        3959.594719     21.485149   3078.833927  4.198350  1040.792079
 1        4195.596065     18.239645   3466.984201  4.158876   983.177515
 2        4136.209822     19.128114   3265.817082  4.206406   979.644128
 3        4006.619026     23.896104   3049.839838  4.122403   860.694805
 4         745.024000     50.000000    372.514000  3.860000  1975.400000
 5        2273.386667     50.000000   1136.693333  3.600000  1466.666667
 6        3307.395000     42.500000   1973.410000  3.375000   557.250000
 7        1555.501667     40.000000    945.618333  4.150000  2343.666667
 8       16856.986000      5.000000  15963.230000  3.640000   586.800000
 9        1697.322000     28.000000   1154.410000  3.720000  3130.600000
 10       2303.200000     26.000000   1681.144000  4.820000  2182.600000
 11        953.213333      8.333333    862.373333  3.733333  2032.333333

         delivery_days  is_prime  was_returned  wishlist_count  cart_add_count
cluster
-1            4.023161  0.529973       0.49455      248.843324     1576.064033
 0            3.544554  0.000000       0.00000      234.306931      484.666667
 1            3.689349  1.000000       1.00000      241.612426      439.085799
 2            3.519573  1.000000       0.00000      230.537367      446.423488
 3            3.269481  0.000000       1.00000      251.272727      373.996753
 4            3.200000  1.000000       1.00000      125.000000      788.600000
 5            5.000000  0.000000       0.00000       41.333333      400.333333
 6            1.750000  1.000000       1.00000      283.000000      107.750000
 7            3.000000  0.000000       0.00000      358.666667     1806.000000
 8            4.400000  0.000000       0.00000      439.000000      204.400000
 9            1.200000  0.000000       1.00000      404.600000     2311.000000
 10           2.600000  0.000000       1.00000      185.400000     1500.600000
 11           7.000000  0.000000       0.00000      235.333333     1070.666667

In [62]:
# tuning ranges
eps_values = [0.5, 0.8, 1.0, 1.2, 1.5, 1.8, 2.0]
min_samples_values = [3, 5, 7, 10]

# results store karne ke liye
results = []

for eps in eps_values:
    for min_s in min_samples_values:
        
        # model
        model = DBSCAN(eps=eps, min_samples=min_s)
        labels = model.fit_predict(x_scl)
        
        # cluster count
        n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
        noise_points = list(labels).count(-1)
        
        # silhouette score only if at least 2 clusters exist
        if n_clusters > 1:
            score = silhouette_score(x_scl, labels)
        else:
            score = -1
        
        results.append([eps, min_s, n_clusters, noise_points, score])

In [63]:
# result dataframe
tuning_df = pd.DataFrame(results, columns=[
    "eps", "min_samples", "n_clusters", "noise_points", "silhouette_score"
])

print(tuning_df)

    eps  min_samples  n_clusters  noise_points  silhouette_score
0   0.5            3           0          2000         -1.000000
1   0.5            5           0          2000         -1.000000
2   0.5            7           0          2000         -1.000000
3   0.5           10           0          2000         -1.000000
4   0.8            3          96          1534         -0.333332
5   0.8            5          13          1913         -0.349986
6   0.8            7           1          1993         -1.000000
7   0.8           10           0          2000         -1.000000
8   1.0            3          53           960         -0.254273
9   1.0            5          29          1331         -0.259203
10  1.0            7          23          1576         -0.284342
11  1.0           10           7          1885         -0.301695
12  1.2            3          21           550         -0.114842
13  1.2            5          12           734         -0.115510
14  1.2            7           7           893         -0.062039
15  1.2           10           5          1164         -0.068657
16  1.5            3          14           314          0.043089
17  1.5            5           5           384          0.099429
18  1.5            7           5           417          0.088609
19  1.5           10           4           463          0.110372
20  1.8            3          17           167          0.091226
21  1.8            5          12           238          0.077915
22  1.8            7           4           296          0.136768
23  1.8           10           4           316          0.134555
24  2.0            3          15            96          0.100869
25  2.0            5           8           159          0.106227
26  2.0            7           7           204          0.096552
27  2.0           10           4           257          0.138927